name        : libdvdread
version     : 5.0.0
release     : 6
source      :
    - http://download.videolan.org/videolan/libdvdread/5.0.0/libdvdread-5.0.0.tar.bz2 : 66fb1a3a42aa0c56b02547f69c7eb0438c5beeaf21aee2ae2c6aa23ea8305f14
homepage    : http://www.videolan.org/index.html
license     : GPL-2.0
component   : multimedia.library
summary     : DVD reading library
description : |
    libdvdread is a library which provides a simple foundation for reading DVDs.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
