name       : libdvdread
version    : 6.1.3
release    : 13
source     :
    - https://download.videolan.org/pub/videolan/libdvdread/6.1.3/libdvdread-6.1.3.tar.bz2 : ce35454997a208cbe50e91232f0e73fb1ac3471965813a13b8730a8f18a15369
homepage   : https://www.videolan.org/developers/libdvdnav.html
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD reading library
description: |
    libdvdread is a library which provides a simple foundation for reading DVDs.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
