name       : libdvdread
version    : 6.1.1
release    : 9
source     :
    - https://download.videolan.org/pub/videolan/libdvdread/6.1.1/libdvdread-6.1.1.tar.bz2 : 3e357309a17c5be3731385b9eabda6b7e3fa010f46022a06f104553bf8e21796
homepage   : https://www.videolan.org/index.html
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD reading library
description: |
    libdvdread is a library which provides a simple foundation for reading DVDs.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
